// This file was autogenerated by ../c4ms/closure/Library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../../../devEnv/testRunner.js', ['remobid.devEnv.TestRunner'], ['goog.array']);
goog.addDependency('../../../../../../src/common/storage/localstorage.js', ['remobid.common.storage.LocalStorage', 'remobid.common.storage.LocalStorage.DataType'], ['goog.array', 'goog.json', 'goog.object', 'remobid.common.storage.StorageErrorType', 'remobid.common.storage.StorageInterface']);
goog.addDependency('../../../../../../src/common/storage/storageErrorType_enum.js', ['remobid.common.storage.StorageErrorType'], []);
goog.addDependency('../../../../../../src/common/storage/storage_interface.js', ['remobid.common.storage.StorageInterface'], []);
