// This file was autogenerated by ../c4ms/closure/Library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../devEnv/testRunner.js', ['remobid.devEnv.TestRunner'], ['goog.array']);
goog.addDependency('../../../../src/common/cache/localcache.js', ['remobid.common.cache.LocalCache'], ['remobid.common.storage.LocalStorage']);
goog.addDependency('../../../../src/common/net/restmanager.js', ['remobid.common.net.RestManager'], ['goog.crypt.base64', 'goog.net.XhrManager']);
goog.addDependency('../../../../src/common/storage/localstorage.js', ['remobid.common.storage.LocalStorage', 'remobid.common.storage.LocalStorage.DataType'], ['goog.array', 'goog.json', 'goog.object', 'remobid.common.storage.StorageBase', 'remobid.common.storage.StorageErrorType']);
goog.addDependency('../../../../src/common/storage/rest.js', ['remobid.common.storage.Rest'], ['remobid.common.net.RestManager', 'remobid.common.storage.StorageBase', 'remobid.common.storage.StorageErrorType']);
goog.addDependency('../../../../src/common/storage/storageBase.js', ['remobid.common.storage.StorageBase'], ['goog.Disposable']);
goog.addDependency('../../../../src/common/storage/storageErrorType_enum.js', ['remobid.common.storage.StorageErrorType'], []);
goog.addDependency('../../../../src/common/storage/storage_interface.js', ['remobid.common.storage.StorageInterface'], []);
goog.addDependency('../../../../test/mock/browser/localstorage.js', ['remobid.test.mock.browser.LocalStorage'], ['goog.object']);
